[tool.poetry]
name = "hwi"
version = "2.0.0"
description = "A library for working with Bitcoin hardware wallets"
authors = ["Andrew Chow <andrew@achow101.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bitcoin-core/HWI"
homepage = "https://github.com/bitcoin-core/HWI"
exclude = ["docs/", "test/"]
include = ["hwilib/**/*.py", "udev/", "hwilib/py.typed"]
packages = [
    { include = "hwi.py" },
    { include = "hwi-qt.py" },
    { include = "hwilib" },
]

[tool.poetry.dependencies]
python = "^3.6,<3.10"
hidapi = "~0"
ecdsa = "~0"
pyaes = "^1.6"
mnemonic = "~0"
typing-extensions = "^3.7"
libusb1 = "^1.7"
pyside2 = { version = "^5.14.0", optional = true }
bitbox02 = ">=5.2.0,<6.0.0"

[tool.poetry.extras]
qt = ["pyside2"]

[tool.poetry.dev-dependencies]
pyinstaller = "^4.0"
pywin32-ctypes = {version = "^0.2.0",platform = "win32"}
pefile = {version = "^2019.4",platform = "win32"}
macholib = {version = "^1.11",platform = "darwin"}
autopep8 = "^1.4"
flake8 = "^3.7"
mypy = "^0.790"
sphinx = "^3.2.1"
sphinx-rtd-theme = "^0.5.1"
sphinxcontrib-autoprogram = "^0.1.6"

[tool.poetry.scripts]
hwi = 'hwilib._cli:main'
hwi-qt = 'hwilib._gui:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
