[tool.poetry]
name = "hwi"
version = "1.1.2-rc.2"
description = "A library for working with Bitcoin hardware wallets"
authors = ["Andrew Chow <andrew@achow101.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bitcoin-core/HWI"
homepage = "https://github.com/bitcoin-core/HWI"
exclude = ["docs/", "test/"]
include = ["hwilib/**/*.py", "udev/"]
packages = [
    { include = "hwi.py" },
    { include = "hwi-qt.py" },
    { include = "hwilib" },
]

[tool.poetry.dependencies]
python = "^3.6,<3.9"
hidapi = "^0.7.99"
ecdsa = "^0.13.0"
pyaes = "^1.6"
mnemonic = "^0.18.0"
typing-extensions = "^3.7"
libusb1 = "^1.7"
pyside2 = { version = "^5.14.0", optional = true }

[tool.poetry.extras]
qt = ["pyside2"]

[tool.poetry.dev-dependencies]
pyinstaller = "^3.4"
pywin32-ctypes = {version = "^0.2.0",platform = "win32"}
pefile = {version = "^2019.4",platform = "win32"}
macholib = {version = "^1.11",platform = "darwin"}
autopep8 = "^1.4"
flake8 = "^3.7"

[tool.poetry.scripts]
hwi = 'hwilib.cli:main'
hwi-qt = 'hwilib.gui:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
